name: Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite iniciar manualmente o workflow

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Atualizado para v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2 # Atualizado para v2
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        env:
          TF_VAR_azure_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          TF_VAR_azure_client_id: ${{ secrets.ARM_CLIENT_ID }}
          TF_VAR_azure_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
          TF_VAR_azure_tenant_id: ${{ secrets.ARM_TENANT_ID }}
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        env:
          TF_VAR_azure_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          TF_VAR_azure_client_id: ${{ secrets.ARM_CLIENT_ID }}
          TF_VAR_azure_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
          TF_VAR_azure_tenant_id: ${{ secrets.ARM_TENANT_ID }}
        run: terraform apply -auto-approve tfplan
